baseurl: https://mltconsecol.github.io
languageCode: en-us
title: MikeTreglia
theme: blackburn
author: Mike Treglia
copyright: '&copy; Michael L. Treglia<br/>All rights reserved.'
canonifyurls: yes
paginate: 10
indexes:
  tag: tags
  topic: topics
params:
  brand: MikeTreglia
  dateFormat: 02 Jan 2006
  # disqus: Your Disqus shortname
  googleAnalytics: "UA-6888715-1"
  highlightjs: ocean
  subtitle: "Spatial Data • Conservation Science"
  relativeurls: true
markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: home
      name: Home
      pre: <i class='fa fa-home fa-fw'></i>
      url: /
      weight: 1
    - identifier: about
      name: About
      pre: <i class='fa fa-user fa-fw'></i>
      url: /about/
      weight: 2
    - identifier: research
      name: "Research"
      pre: "<i class='fa fa-chart-area fa-fw'></i>"
      url: /research/
      weight: 3
    - identifier: teaching
      name: "Teaching"
      pre: "<i class='fa fa-university fa-fw'></i>"
      weight: 4
      url: "/teaching/"
    - identifier: code
      name: "Coding Projects"
      pre: "<i class='fa fa-code fa-fw'></i>"
      weight: 5
      url: "/code/"
    - identifier: post
      name: Posts
      pre: <i class='fa fa-list fa-fw'></i>
      url: /post/
      weight: 6
    - identifier: contact
      name: Contact
      pre: <i class='fa fa-envelope fa-fw'></i>
      url: /contact/
      weight: 7
markup.goldmark.renderer:
  -unsafe: true
        
social:
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter: "miketreglia"
  #facebook = "*"
  instagram: "m1ketreglia"
  github: "mtreg"
  #stackoverflow = "*"
  #linkedin = "*"
